// packages/@wps-jsapi/wpp_vue/src/components/Dialog.vue
<template>
  <div class="hello">
    <div class="global">
      <div class="divItem">这是一个网页，按<span style="font-weight: bolder">"F12"</span>可以打开调试器。</div>
      <div class="divItem">
        这个示例展示了wps加载项的相关基础能力，与B/S业务系统的交互，请用浏览器打开：
        <span style="font-weight: bolder; color: slateblue; cursor: pointer" @click="onOpenWeb()">{{ DemoSpan }}</span>
      </div>
      <div class="divItem">
        开发文档: <span style="font-weight: bolder; color: slateblue">https://open.wps.cn/docs/office</span>
      </div>
      <hr />
      <div class="divItem">
        <button style="margin: 3px" @click="onDocNameClick()">取文件名</button>
        <button style="margin: 3px" @click="onbuttonclick('createTaskPane')">创建任务窗格</button>
        <button style="margin: 3px" @click="onbuttonclick('newDoc')">新建文件</button>
        <button style="margin: 3px" @click="onbuttonclick('addString')">文档开头添加字符串</button>
      </div>
      <hr />
      <div class="divItem">
        文档文件名为：<span>{{ docName }}</span>
      </div>
    </div>
  </div>
</template>

<script>
import dlgFunc from "./js/dialog.js";
import axios from "axios";
export default {
  name: "Dialog",
  data() {
    return {
      DemoSpan: "",
      docName: "",
    };
  },
  methods: {
    onbuttonclick(id) {
      return dlgFunc.onbuttonclick(id);
    },
    onDocNameClick() {
      this.docName = dlgFunc.onbuttonclick("getDocName");
    },
    onOpenWeb() {
      dlgFunc.onbuttonclick("openWeb", this.DemoSpan);
    },
  },
  mounted() {
    axios.get("/.debugTemp/NotifyDemoUrl").then((res) => {
      this.DemoSpan = res.data;
    });
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.global {
  font-size: 15px;
  min-height: 95%;
}
.divItem {
  margin-left: 5px;
  margin-bottom: 18px;
  font-size: 15px;
  word-wrap: break-word;
}
</style>

// packages/@wps-jsapi/wpp_react/src/components/dialog.js
import React, { Component } from "react";
import { connect } from "react-redux";
import { getDocName, createTaskpane, newDoc, addString, closeDoc, setDemoSpan, openWeb } from "../actions/dialog";
import "./dialog.css";
import axios from "axios";

class Dialog extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  componentDidMount() {
    axios.get("/.debugTemp/NotifyDemoUrl").then((res) => {
      const { setDemoSpan } = this.props;
      setDemoSpan(res.data);
    });
  }

  onDocNameClick = () => {
    const { getDocName } = this.props;
    getDocName();
  };

  onCreateTaskpane = () => {
    const { createTaskpane } = this.props;
    createTaskpane();
  };

  onCreateDoc = () => {
    const { newDoc } = this.props;
    newDoc();
  };

  onAddString = () => {
    const { addString } = this.props;
    addString();
  };

  onCloseDoc = () => {
    const { closeDoc } = this.props;
    closeDoc();
  };

  onOpenWeb = () => {
    const { openWeb } = this.props;
    openWeb();
  };

  render() {
    const { docName, demoSpan } = this.props;

    return (
      <div>
        <div className="divItem">
          这是一个网页，按<span className="debug">"F12"</span>可以打开调试器。
        </div>
        <div className="divItem">
          这个示例展示了wps加载项的相关基础能力，与B/S业务系统的交互，请用浏览器打开：
          <span className="docs" onClick={this.onOpenWeb}>
            {demoSpan}
          </span>
        </div>
        <div className="divItem">
          开发文档: <span className="docs">https://open.wps.cn/docs/office</span>
        </div>
        <div>
          <button onClick={this.onDocNameClick}>取文件名</button>
          <button onClick={this.onCreateTaskpane}>创建任务窗格</button>
          <button onClick={this.onCreateDoc}>新建文件</button>
          <button onClick={this.onAddString}>文档开头添加字符串</button>
          <button onClick={this.onCloseDoc}>关闭文件</button>
        </div>
        <hr />
        <div>
          文档文件名为：<span>{docName}</span>
        </div>
      </div>
    );
  }
}

const mapStateToProps = (state) => {
  return {
    docName: state.dialog.get("docName"),
    demoSpan: state.dialog.get("demoSpan"),
  };
};

export default connect(mapStateToProps, {
  getDocName,
  createTaskpane,
  newDoc,
  addString,
  closeDoc,
  setDemoSpan,
  openWeb,
})(Dialog);
